// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHVjeYlWbGS7L_wHohcaO83Li3OI7bo4',
    appId: '1:790437567348:web:939c723028969f2afeea21',
    messagingSenderId: '790437567348',
    projectId: 'appaviacao-69c6a',
    authDomain: 'appaviacao-69c6a.firebaseapp.com',
    storageBucket: 'appaviacao-69c6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjn1yge1cwURh4Zycj0rW9FHp7mtFzVzM',
    appId: '1:790437567348:android:c526c93749bbd673feea21',
    messagingSenderId: '790437567348',
    projectId: 'appaviacao-69c6a',
    storageBucket: 'appaviacao-69c6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKf0Gr_Nlx7PLmNh2kgrYq8JCmBsnyfI',
    appId: '1:790437567348:ios:cd4a025bf8efe91bfeea21',
    messagingSenderId: '790437567348',
    projectId: 'appaviacao-69c6a',
    storageBucket: 'appaviacao-69c6a.firebasestorage.app',
    iosBundleId: 'com.example.airHubSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPKf0Gr_Nlx7PLmNh2kgrYq8JCmBsnyfI',
    appId: '1:790437567348:ios:cd4a025bf8efe91bfeea21',
    messagingSenderId: '790437567348',
    projectId: 'appaviacao-69c6a',
    storageBucket: 'appaviacao-69c6a.firebasestorage.app',
    iosBundleId: 'com.example.airHubSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUHVjeYlWbGS7L_wHohcaO83Li3OI7bo4',
    appId: '1:790437567348:web:690967404a4b500efeea21',
    messagingSenderId: '790437567348',
    projectId: 'appaviacao-69c6a',
    authDomain: 'appaviacao-69c6a.firebaseapp.com',
    storageBucket: 'appaviacao-69c6a.firebasestorage.app',
  );

}